services:
  app:
    build: .
    env_file:
      .env
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./src/var:/var/www/html/var:delegated
      - ./src/vendor:/var/www/html/vendor:delegated
    working_dir: /var/www/html
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - ./docker/mysql:/var/lib/mysql:delegated
    restart: always